/**
 * ============================================================================
 * Module: curateFullBody
 * ----------------------------------------------------------------------------
 * Purpose:
 * Curate a complete Full Body workout from the Exercise Library.
 *
 * Full Body differs from Grab & Go and Flow Day:
 *
 *   Grab & Go / Flow Day → one Card per curation call
 *   Full Body            → a workout (multiple groups) per curation call
 *
 * The workout is a set of groups. Each group is a small cluster of
 * exercises performed together as a superset, circuit, or straight set.
 *
 * Group type is determined by group size:
 *   - 1 exercise  → straightSets
 *   - 2 exercises → superset
 *   - 3 exercises → circuit
 *
 * Prescriptions are generated by engine/scoring.js. Curation asks scoring
 * for a prescription per exercise, then expands it into the set array the
 * workout shape uses.
 *
 * Architecture:
 *
 * User Selection + Exercise Count
 *      ↓
 * filterExercises()
 *      ↓
 * Purpose Exclusion Filter
 *      ↓
 * Pool Selection (variety by movement pattern)
 *      ↓
 * Grouping (by movement chain, tiebroken by pattern)
 *      ↓
 * Prescription generation (per exercise)
 *      ↓
 * Workout
 *
 * This module does NOT:
 * - define vocabulary
 * - modify Exercise Library entries
 * - own filtering rules
 * - score exercises for ranking
 * - manage weekly history
 * - persist workouts
 * - handle warm-up / cool-down
 * - own the prescription logic (scoring does)
 *
 * ============================================================================
 */

import { filterExercises } from "./filters";
import { generatePrescription, expandPrescriptionToSets } from "./scoring";

/*
 * --------------------------------------------------------------------------
 * Purposes That Belong to Warm-Up / Cool-Down, Not Workout Content
 * --------------------------------------------------------------------------
 */

const WORKOUT_EXCLUDED_PURPOSES = new Set([
  "jointPreparation",
  "recovery",
  "decompression",
  "downshift",
  "rangeDevelopment",
]);

/*
 * --------------------------------------------------------------------------
 * Grouping Targets
 * --------------------------------------------------------------------------
 */

const MIN_EXERCISES_PER_CARD = 2;
const MAX_EXERCISES_PER_CARD = 3;

/*
 * --------------------------------------------------------------------------
 * Group Type
 * --------------------------------------------------------------------------
 *
 * Derived from group size. See module header.
 */

function groupTypeForSize(size) {
  if (size <= 1) {
    return "straightSets";
  }

  if (size === 2) {
    return "superset";
  }

  return "circuit";
}

/*
 * --------------------------------------------------------------------------
 * Purpose Excluded?
 * --------------------------------------------------------------------------
 */

function hasOnlyExcludedPurposes(exercise) {
  const exercisePurposes = exercise.purposes ?? [];

  if (exercisePurposes.length === 0) {
    return false;
  }

  return exercisePurposes.every((purpose) =>
    WORKOUT_EXCLUDED_PURPOSES.has(purpose)
  );
}

/*
 * --------------------------------------------------------------------------
 * Group by Movement Pattern
 * --------------------------------------------------------------------------
 */

function getPrimaryPattern(exercise) {
  return exercise.movementPatterns?.[0] ?? null;
}

/*
 * --------------------------------------------------------------------------
 * Select a Balanced Pool
 * --------------------------------------------------------------------------
 */

function selectBalancedPool(eligibleExercises, requestedCount) {
  if (eligibleExercises.length <= requestedCount) {
    return [...eligibleExercises];
  }

  const patterns = new Map();

  eligibleExercises.forEach((exercise) => {
    const pattern = getPrimaryPattern(exercise) ?? "__unpatterned";

    if (!patterns.has(pattern)) {
      patterns.set(pattern, []);
    }

    patterns.get(pattern).push(exercise);
  });

  const patternOrder = [...patterns.keys()];

  const selected = [];

  let round = 0;

  while (selected.length < requestedCount) {
    let progressedThisRound = false;

    for (const pattern of patternOrder) {
      if (selected.length >= requestedCount) {
        break;
      }

      const bucket = patterns.get(pattern);
      const candidate = bucket[round];

      if (candidate) {
        selected.push(candidate);
        progressedThisRound = true;
      }
    }

    if (!progressedThisRound) {
      break;
    }

    round += 1;
  }

  return selected;
}

/*
 * --------------------------------------------------------------------------
 * Group Pool into Groups
 * --------------------------------------------------------------------------
 *
 * Primary axis:   movement chain
 * Tiebreak axis:  movement pattern
 *
 * Exercises are grouped into clusters of 2-3. We prefer grouping exercises
 * that share a movement chain.
 *
 * Each exercise is expanded into a prescription via scoring, then expanded
 * into a set array.
 */

function getPrimaryChain(exercise) {
  return exercise.movementChains?.[0] ?? "__unchained";
}

function buildExerciseWithPrescription(exercise) {
  const prescription = generatePrescription(exercise);

  return {
    id: exercise.id,
    sets: expandPrescriptionToSets(prescription),
  };
}

function groupPoolIntoGroups(pool) {
  if (pool.length === 0) {
    return [];
  }

  const byChain = new Map();

  pool.forEach((exercise) => {
    const chain = getPrimaryChain(exercise);

    if (!byChain.has(chain)) {
      byChain.set(chain, []);
    }

    byChain.get(chain).push(exercise);
  });

  const groups = [];

  byChain.forEach((chainExercises, chain) => {
    let currentGroup = null;

    chainExercises.forEach((exercise) => {
      const needsNewGroup =
        !currentGroup ||
        currentGroup.exercises.length >= MAX_EXERCISES_PER_CARD;

      if (needsNewGroup) {
        currentGroup = {
          id: createGroupId(chain, groups.length),
          type: "straightSets", // placeholder, set below when group is full
          exercises: [],
        };

        groups.push(currentGroup);
      }

      currentGroup.exercises.push(
        buildExerciseWithPrescription(exercise)
      );
    });
  });

  /*
   * Now that every group is populated, assign its type based on final size.
   */

  groups.forEach((group) => {
    group.type = groupTypeForSize(group.exercises.length);
  });

  return groups;
}

/*
 * --------------------------------------------------------------------------
 * Order Groups
 * --------------------------------------------------------------------------
 *
 * Rough ordering so the workout reads coherently.
 */

const CHAIN_ORDER = [
  "posterior",
  "anterior",
  "lateral",
  "spiral",
  "__unchained",
];

function orderGroups(groups, pool) {
  const poolById = new Map(pool.map((exercise) => [exercise.id, exercise]));

  return [...groups].sort((a, b) => {
    const aExercise = poolById.get(a.exercises[0]?.id);
    const bExercise = poolById.get(b.exercises[0]?.id);

    const aChain = aExercise ? getPrimaryChain(aExercise) : "__unchained";
    const bChain = bExercise ? getPrimaryChain(bExercise) : "__unchained";

    const aIndex = CHAIN_ORDER.indexOf(aChain);
    const bIndex = CHAIN_ORDER.indexOf(bChain);

    return (
      (aIndex === -1 ? CHAIN_ORDER.length : aIndex) -
      (bIndex === -1 ? CHAIN_ORDER.length : bIndex)
    );
  });
}

/*
 * --------------------------------------------------------------------------
 * Group ID
 * --------------------------------------------------------------------------
 */

function createGroupId(chain, index) {
  return `full-body-${chain}-${index}-${Date.now()}`;
}

/*
 * --------------------------------------------------------------------------
 * Public Entry Point
 * --------------------------------------------------------------------------
 *
 * Curate a Full Body workout.
 *
 * @param {Object[]} exercises
 *   The full Exercise Library.
 *
 * @param {Object} selection
 *   { purposes, classifications, equipment } from FilterPanel.
 *
 * @param {number} exerciseCount
 *   Requested number of exercises across the workout.
 *
 * @param {string[]} excludedExerciseIds
 *   Exercise IDs to exclude (typically already used elsewhere).
 *
 * @returns {Object|null}
 *   A workout object, or null when nothing eligible exists.
 */

export function curateFullBody({
  exercises,
  selection,
  exerciseCount,
  excludedExerciseIds = [],
}) {
  const eligibleByFilter = filterExercises(
    exercises,
    selection,
    excludedExerciseIds
  );

  const eligibleForWorkout = eligibleByFilter.filter(
    (exercise) => !hasOnlyExcludedPurposes(exercise)
  );

  if (eligibleForWorkout.length === 0) {
    return null;
  }

  const pool = selectBalancedPool(
    eligibleForWorkout,
    exerciseCount
  );

  if (pool.length === 0) {
    return null;
  }

  const groups = groupPoolIntoGroups(pool);

  const orderedGroups = orderGroups(groups, pool);

  return {
    state: "draft",
    plannedDuration: null,      // set by the page from the config
    actualDuration: null,       // reserved for the timer
    cursor: null,
    groups: orderedGroups,
  };
}
